
import java.sql.DriverManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author Pablo Pierre
 */
public class PessoasFrame04 extends javax.swing.JFrame {

    /**
     * Creates new form AgendaFrame
     */
    public PessoasFrame04() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bConectar04 = new javax.swing.JButton();
        bDesconectar04 = new javax.swing.JButton();
        txtId_Pessoas04 = new javax.swing.JTextField();
        bConsultar04 = new javax.swing.JButton();
        txtNome04 = new javax.swing.JTextField();
        txtRating04 = new javax.swing.JTextField();
        txtIniciante04 = new javax.swing.JTextField();
        txtMensagem104 = new javax.swing.JTextField();
        txtMensagem204 = new javax.swing.JTextField();
        TxtQuery04 = new javax.swing.JTextField();
        bQuery04 = new javax.swing.JToggleButton();
        bAnterior04 = new javax.swing.JButton();
        bProximo04 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bConectar04.setText("Conectar");
        bConectar04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectar04ActionPerformed(evt);
            }
        });

        bDesconectar04.setText("Desconectar");
        bDesconectar04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesconectar04ActionPerformed(evt);
            }
        });

        bConsultar04.setText("Consultar");
        bConsultar04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultar04ActionPerformed(evt);
            }
        });

        txtNome04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome04ActionPerformed(evt);
            }
        });

        TxtQuery04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtQuery04ActionPerformed(evt);
            }
        });

        bQuery04.setText("Executar Query");
        bQuery04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuery04ActionPerformed(evt);
            }
        });

        bAnterior04.setText("<<");
        bAnterior04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnterior04ActionPerformed(evt);
            }
        });

        bProximo04.setText(">>");
        bProximo04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProximo04ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId_Pessoas04, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bConsultar04)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome04)
                                .addGap(131, 131, 131)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bDesconectar04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bConectar04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIniciante04, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRating04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMensagem104, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                                    .addComponent(TxtQuery04, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bAnterior04, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(bProximo04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtMensagem204, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bQuery04, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bConectar04)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId_Pessoas04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bConsultar04)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDesconectar04)
                    .addComponent(txtNome04, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtRating04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtIniciante04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(bQuery04)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bProximo04, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtQuery04, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bAnterior04)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(txtMensagem104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtMensagem204, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConectar04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectar04ActionPerformed
        // TODO add your handling code here:
        String URL = "jdbc:sqlserver://localhost;databaseName=" + "Pessoas"
                + ";user=" + "Igor" + ";password=" + "igor";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cn = DriverManager.getConnection(URL);
            txtMensagem204.setText("conexão realizada!");
        } catch (Exception ex) {
            cn = null;
            txtMensagem204.setText("conexão não realizada!");
        }

    }//GEN-LAST:event_bConectar04ActionPerformed

    private void bDesconectar04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesconectar04ActionPerformed
        // TODO add your handling code here:
        if (cn != null) {
            try {
                cn.close();
            } catch (Exception ex) {
            }
            cn = null;
        }
    }//GEN-LAST:event_bDesconectar04ActionPerformed

    private void bConsultar04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultar04ActionPerformed

        TxtQuery04.setText("");
        txtId_Pessoas04.setText("");
        txtIniciante04.setText("");
        txtNome04.setText("");
        txtRating04.setText("");
        txtMensagem104.setText("");
        txtMensagem204.setText("");

        try {
            if (cn != null) {
                Integer id_Pessoa = Integer.parseInt(txtId_Pessoas04.getText());
                PessoasDAO04 pessoaDao = new PessoasDAO04(cn);
                PessoasPO04 pessoaPo = pessoaDao.GetPessoaById(id_Pessoa);
                
                if (pessoaPo != null) {
                    txtId_Pessoas04.setText(pessoaPo.id_Pessoa.toString());
                    txtNome04.setText(pessoaPo.nome);
                    txtRating04.setText(String.valueOf(pessoaPo.rating));
                    
                    if (pessoaPo.iniciante != null) {
                        if (pessoaPo.iniciante == false) {
                            txtIniciante04.setText("False");                            
                        } else {
                            txtIniciante04.setText("True");
                        }
                    } else {
                        txtIniciante04.setText("Sem informação!");
                    }
                    
                }
                txtMensagem204.setText("");
            }
        } catch (Exception ex) {
            txtMensagem204.setText(ex.getMessage());
        }
    }//GEN-LAST:event_bConsultar04ActionPerformed

    private void TxtQuery04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQuery04ActionPerformed
        String strQuery = TxtQuery04.getText();
    }//GEN-LAST:event_TxtQuery04ActionPerformed

    private void bQuery04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuery04ActionPerformed

        txtId_Pessoas04.setText("");
        txtNome04.setText("");
        txtIniciante04.setText("");
        txtRating04.setText("");
        txtMensagem104.setText("");
        txtMensagem204.setText("");

        try {
            if (cn != null) {
                String strQuery = TxtQuery04.getText();
                PessoasDAO04 pessoaDao = new PessoasDAO04(cn);
                pessoas = pessoaDao.GetPessoaByQuery(strQuery);
                
                if (pessoas.size() > 0) {
                    index = 0;
                    PessoasPO04 pessoaPo = pessoas.get(index);
                    Mostra(pessoaPo);
                    txtMensagem104.setText( "1 de " + pessoas.size() + " registros!");
                    txtMensagem204.setText(pessoas.size() + " registros encontrados!");
                }else{
                    txtMensagem204.setText("0 registros encontrados!");
                }
                
                
            }
        } catch (Exception ex) {
            txtMensagem204.setText(ex.getMessage());
        }

    }//GEN-LAST:event_bQuery04ActionPerformed

    private void bAnterior04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnterior04ActionPerformed
        Mover(-1);
    }//GEN-LAST:event_bAnterior04ActionPerformed

    private void bProximo04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProximo04ActionPerformed
        Mover(1);
    }//GEN-LAST:event_bProximo04ActionPerformed

    private void txtNome04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome04ActionPerformed
    
    private void Mover(int inc) {
        if (pessoas != null && (index + inc) >= 0 && (index + inc) < pessoas.size()) {
            
            txtIniciante04.setText("");
            
            index = index + inc;
            PessoasPO04 pessoaPo = pessoas.get(index);
            Mostra(pessoaPo);
            txtMensagem104.setText((index + 1) + " de " + pessoas.size() + " registros!");
        }
    }
    
    private void Mostra(PessoasPO04 pessoaPo) {
        if (pessoaPo != null) {
            txtId_Pessoas04.setText(pessoaPo.id_Pessoa.toString());
                    txtNome04.setText(pessoaPo.nome);
                    txtRating04.setText(String.valueOf(pessoaPo.rating));
                    
                    if (pessoaPo.iniciante != null) {
                        if (pessoaPo.iniciante == false) {
                            txtIniciante04.setText("False");                            
                        } else {
                            txtIniciante04.setText("True");
                        }
                    } else {
                        txtIniciante04.setText("Sem informação!");
                    }
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoasFrame04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoasFrame04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoasFrame04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoasFrame04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoasFrame04().setVisible(true);
            }
        });
    }
    
    private Connection cn;
    private int index = -1;
    private ArrayList<PessoasPO04> pessoas;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtQuery04;
    private javax.swing.JButton bAnterior04;
    private javax.swing.JButton bConectar04;
    private javax.swing.JButton bConsultar04;
    private javax.swing.JButton bDesconectar04;
    private javax.swing.JButton bProximo04;
    private javax.swing.JToggleButton bQuery04;
    private javax.swing.JTextField txtId_Pessoas04;
    private javax.swing.JTextField txtIniciante04;
    private javax.swing.JTextField txtMensagem104;
    private javax.swing.JTextField txtMensagem204;
    private javax.swing.JTextField txtNome04;
    private javax.swing.JTextField txtRating04;
    // End of variables declaration//GEN-END:variables
}
